version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
  web:
    env_file: .env
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - ROR_BASE_URL=http://localhost
    build: .
    image: rorcommunity/ror-api
    ports:
      - "80:80"
      - "2222:22"
    volumes:
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    depends_on:
      - elasticsearch
