version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
  web:
    env_file: .env
    environment:
      - ELASTIC_PASSWORD=changeme
      - ELASTIC_SEARCH=http://elasticsearch:9200
    build: .
    image: rorcommunity/ror-api
    ports:
      - "9292:80"
    volumes:
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./data:/home/app/webapp/data
      - ./spec:/home/app/webapp/spec
      - ./app.rb:/home/app/webapp/app.rb
      - ./vendor:/home/app/vendor
    depends_on:
      - elasticsearch
