version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
  rorapi:
    build: .
    image: rorcommunity/ror-api
    environment:
      - ELASTIC_PASSWORD=changeme
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    volumes:
      - .:/code
    ports:
      - "80:8000"
    working_dir: /code
    depends_on:
      - elasticsearch
    command: "python manage.py runserver 0.0.0.0:8000"
